### ISSUE TITLE
Markdown metadata for `date` field is all in 1970

### ISSUE THREAD

**Issue by stefmolin** [pyOpenSci/python-package-guide#507]
I just noticed that the `date` field in the metadata for several Markdown files (for example `tutorials/publish-conda-forge.md`) states they were written in 1970. It looks like these were introduced in #488.

**Comment by stefmolin** [comment]
For my website, I use a tool in my GitHub Actions workflow to restore the modified time to my post Markdown files so that the RSS feed always has the true last modified time:

```yaml
- name: Checkout
  uses: actions/checkout@v4
  with:
    fetch-depth: 0  # need to fetch all commits for git restore-mtime

- name: Restore timestamps
  run: sudo apt-get install git-restore-mtime && git restore-mtime
```

Then, you can remove this field from the metadata of each file, and in Python, you can do `Path(file).stat().st_mtime` to grab the timestamp for your RSS feed (see https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat).
